spring.application.name=spring-jpa-demo

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/learn_spring
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# MongoDB
#spring.data.mongodb.uri=mongodb://admin:123456@localhost:27027/learn_spring
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27027
#spring.data.mongodb.database=learn_spring
#spring.data.mongodb.username=admin
#spring.data.mongodb.password=123456